delete from public.outreach;
delete from public.jobs;

insert into public.jobs (title, company, location, work_mode, url, source, description, fit_reason, fit_score, priority, verified_at, is_active) values
('HR Business Partner / Partner Biznesowy HR','Aliaxis','Wrocław (IT Hub)','hybrid','https://aliaxis.wd3.myworkdayjobs.com/en-US/Aliaxis/job/PL---Wroclaw/HR-Business-Partner---Partner-Biznesowy-HR_R-57949-1','Workday (Aliaxis careers)','HRBP EEG (PL, RS, LT, HU, CZ, GR) w hubie IT we Wrocławiu. First-line HR dla managerów, onboarding/offboarding, wsparcie rekrutacji, EVP/kultura nowego biura, inicjatywy EMEA HR. PL+EN. PostingAvailable=true (verified 2026-09-09).','Najbliższy fit: multi-country People Ops + HRBP w hubie WR, EN, lifecycle, kultura biura — blisko APMC/Laminar/Deel.',5,1,'2026-09-09',true),
('HR Business Partner','Zrzutka.pl','Wrocław','onsite','https://rocketjobs.pl/oferta-pracy/zrzutka-pl-hr-business-partner-wroclaw-hr-hr','RocketJobs','Senior HRBP soft HR: rozwój, zaangażowanie, rekrutacja, onboarding/EX, compensations, analytics. B2B, stacjonarnie al. Karkonoska 59. Aktywna do ~07.10.2026.','Product company Wrocław + pełny People Partner ownership. Idealny kulturowo (nie GBS).',5,1,'2026-09-09',true),
('HR Specialist','ASTEK Polska','Wrocław','hybrid','https://rocketjobs.pl/oferta-pracy/astek-polska-hr-specialist-wroclaw-hr-hr','RocketJobs','HR operations + administracja kadrowa PL, payroll input, Płatnik/ePUE. Mid, 10–12.5k UoP, hybrid. Oferta aktywna (live).','Twarde People Ops + kadry PL — bezpośrednie przełożenie z payroll/time-off Marty.',4,1,'2026-09-09',true),
('People Operations Coordinator (6–8 Month FTC)','Antal (client)','Wrocław','hybrid','https://rocketjobs.pl/oferta-pracy/antal-sp-z-o-o--people-operations-coordinator-6-8-month-fixed-term-contract--wroclaw-hr-hr','RocketJobs','People Ops Coordinator dla międzynarodowego klienta: HR ops multi-country Europe, Workday, trackery, transformacja procesów. FTC 6–8 mies. Hybrid WR.','Dokładny tytuł People Ops + multi-country + Workday. FTC = bridge, ale scope idealny.',4,1,'2026-09-09',true),
('Regular Payroll Specialist','Spyrosoft','Wrocław','hybrid','https://rocketjobs.pl/oferta-pracy/spyrosoft-regular-payroll-specialist-wroclaw-hr-hr','RocketJobs','Payroll employees+contractors, Enova365, PL labour law, EN B2. 7.2–9.5k. Active ~20 dni.','WR product/IT + contractors/payroll — silny overlap z ARC/Laminar.',4,1,'2026-09-09',true),
('Payroll Specialist (Regular)','Spyrosoft','Wrocław','hybrid','https://rocketjobs.pl/oferta-pracy/spyrosoft-payroll-specialist-regular--wroclaw-hr-hr','RocketJobs','Druga aktywna oferta payroll Spyrosoft WR, hybrid, 7.2–9.5k, Enova365 + EN.','Potwierdzenie otwartego zapotrzebowania payroll/ops w Spyrosoft WR.',4,1,'2026-09-09',true),
('HR Business Partner','EduGO P.S.A.','Remote (PL, listing WR)','remote','https://rocketjobs.pl/oferta-pracy/edugo-p-s-a--hr-business-partner-wroclaw-hr-hr','RocketJobs','HRBP remote, 15–18k UoP, EduTech. Listing dostępny z Wrocławia.','Remote HRBP z PL — da się robić z WR; product/edtech kontekst.',4,1,'2026-09-09',true),
('HR Business Partner Lead / HR Service Delivery Leader','Link Group','Remote (listing WR)','remote','https://rocketjobs.pl/oferta-pracy/link-group-hr-business-partner-lead-hr-service-delivery-leader-wroclaw-hr-hr','RocketJobs','HRBP Lead / Service Delivery, B2B 130–160 PLN/h, remote. Leadership HR service delivery.','Senior People Ops/service delivery remote z WR. Stretch seniority.',3,2,'2026-09-09',true),
('HR Manager','Soliści Adventure Club','Wrocław','onsite','https://rocketjobs.pl/oferta-pracy/solisci-adventure-club-hr-manager-wroclaw-hr-hr','RocketJobs','HR Manager: rekrutacja, budżet, zespół, projekty. UoP/B2B, stacjonarnie WR. Active ~29 dni.','Pełny ownership HR w lokalnej org — generalist; mniejsza skala international.',3,2,'2026-09-09',true),
('Specjalistka / Specjalista ds. płac','VeloBank S.A.','Wrocław','hybrid','https://rocketjobs.pl/oferta-pracy/velobank-s-a--specjalistka-specjalista-ds-plac-wroclaw-hr-hr','RocketJobs','Payroll specialist: prawo pracy, podatki, ZUS. Hybrid WR. Active.','PL payroll overlap; bank = bardziej formalny niż product ops.',3,2,'2026-09-09',true),
('HR Operations Specialist (with German)','Capgemini','Wrocław','hybrid','https://rocketjobs.pl/oferta-pracy/capgemini-hr-operations-specialist-with-german--wroclaw-hr-hr','RocketJobs','HR Ops Specialist, Workday, DE required. Hybrid WR. Wygasa ~3 dni — sprawdź ASAP.','People Ops + Workday, ale DE required + GBS = niższy fit kulturowy.',2,3,'2026-09-09',true);

insert into public.jobs (title, company, location, work_mode, url, source, description, fit_reason, fit_score, priority, verified_at, is_active) values
('Młodszy Specjalista ds. HR (z j. niemieckim)','Capgemini','Wrocław','hybrid','https://rocketjobs.pl/oferta-pracy/capgemini-mlodszy-a-specjalista-ka-ds-hr-z-j-niemieckim--wroclaw-hr-hr','RocketJobs','Junior HR z DE, Capgemini WR. Active.','WR+HR ops entry; junior+DE = słabszy match seniority/język.',2,3,'2026-09-09',true),
('HR Specialist with German','Pyszne.pl','Wrocław','hybrid','https://rocketjobs.pl/oferta-pracy/pyszne-pl-hr-specialist-with-german-wroclaw-hr-hr','RocketJobs','HR Specialist DE, Just Eat Takeaway brand, hybrid WR.','Product/tech employer WR; DE required obniża fit.',2,3,'2026-09-09',true),
('HR Administrator with German','Pyszne.pl','Wrocław','hybrid','https://rocketjobs.pl/oferta-pracy/pyszne-pl-hr-administrator-with-german-wroclaw-hr-hr','RocketJobs','HR Admin DE, hybrid WR.','Admin/ops overlap; DE required.',2,3,'2026-09-09',true),
('Starszy specjalista ds. Kadr i Płac','WORK 4 US','Oława (WR area)','hybrid','https://rocketjobs.pl/oferta-pracy/work-4-us-spolka-z-ograniczona-odpowiedzialnoscia-starszy-specjalista-ds-kadr-i-plac-olawa-hr-hr','RocketJobs','Senior kadry+płace, delegowanie, A1, Optima, cudzoziemcy. Hybrid Oława.','Cross-border employment admin blisko mobility Marty; lokalizacja Oława.',3,2,'2026-09-09',true),
('HR Business Partner / HR Manager (k/m)','ARCOS FM PL / Saller Polbau','Wrocław, Krzyki','onsite','https://www.pracuj.pl/praca/hr-business-partner-hr-manager-k-m-wroclaw-wyscigowa-56c,oferta,1005047030','Pracuj.pl','Punkt kontaktu HR PL + współpraca z HR DE. Rekrutacja, doradztwo, controlling HR. Opublikowana 8.09.2026.','Generalist HRBP + ops + rekrutacja. Cross-border DE (atut, nie hard gate w tytule).',4,1,'2026-09-09',true),
('HR Business Partner (HRBP) (K/M)','Atlas Ward Polska','Wrocław, Krzyki','hybrid','https://www.pracuj.pl/praca/hr-business-partner-hrbp-k-m-wroclaw-zwycieska-41,oferta,1005044437','Pracuj.pl','HRBP hybrid WR. Partner biznesowy dla managerów. Opublikowana 5.09.2026.','Klasyczny HRBP hybrid we Wrocławiu — dobry fit partnerski.',4,1,'2026-09-09',true),
('HR Business Partner','LHH (klient produkcyjny)','Wrocław','onsite','https://www.pracuj.pl/praca/hr-business-partner-wroclaw,oferta,1005018441','Pracuj.pl','HRBP dla klienta produkcyjnego: lifecycle, onboarding, rozwój, KPIs, EN. 11–15k. Uwaga: wygasa ~09.09 — sprawdź status przed aplikacją.','HRBP generalist + data/KPI; produkcja ≠ tech, ale solidny scope.',3,2,'2026-09-09',true),
('HR Manager / HR Builder','Human Group','Wrocław','hybrid','https://www.pracuj.pl/praca/hr-manager-hr-builder-wroclaw,oferta,1005031044','Pracuj.pl','Hands-on HR builder: procesy, rekrutacja, dane, AI/automatyzacja. Hybrid. Ważna do ~16.09.2026.','Szeroki ownership People/HR (nie wąski SSC). Uwaga: agencja, nie product.',4,1,'2026-09-09',true),
('HR Business Partner Grupy (k/m)','Human Group','Wrocław','hybrid','https://www.pracuj.pl/praca/hr-business-partner-grupy-k-m-wroclaw,oferta,1005013549','Pracuj.pl','Partnerstwo z zarządem, onboarding/offboarding, rekrutacja wewnętrzna, polityki HR. 13–18k. Hybrid.','Builder/HRBP ownership — sprawczość jak w mid-size ops.',4,1,'2026-09-09',true),
('HR Operations & Process Specialist','DEKRA (international client)','Wrocław','onsite','https://www.pracuj.pl/praca/hr-operations-process-specialist-wroclaw,oferta,1005049577','Pracuj.pl','Analyze/document HR ops across multiple countries; standardize processes; local compliance. Opublikowana 8.09.2026.','Multi-country HR process ownership — bardzo blisko global people ops Marty.',5,1,'2026-09-09',true),
('HR & Executive Support Specialist','Erste Operations GmbH','Wrocław','hybrid','https://www.pracuj.pl/praca/hr-executive-support-specialist-wroclaw-strzegomska-8-10,oferta,1005039762','Pracuj.pl','Employee lifecycle (recruitment, onboarding, offboarding), dokumentacja, wsparcie local management. 7.5–9.5k. Hybrid/onsite.','Lifecycle + office/exec support — overlap z People & Ops / office coordination.',4,1,'2026-09-09',true),
('Specjalistka / Specjalista ds. Wsparcia Aplikacji HR','Credit Agricole Bank Polska','Wrocław','hybrid','https://www.pracuj.pl/praca/specjalistka-specjalista-ds-wsparcia-aplikacji-hr-wroclaw-legnicka-48,oferta,1005069654','Pracuj.pl','Wsparcie systemów HR, platformy benefitowe, monitoring aplikacji, współpraca z dostawcami. HQ WR.','HRIS/ops systems — Marta zna Deel/HR records; fit techniczno-operacyjny.',3,2,'2026-09-09',true);

insert into public.jobs (title, company, location, work_mode, url, source, description, fit_reason, fit_score, priority, verified_at, is_active) values
('Specjalista ds. Personalnych (K/M)','CEVA Logistics Poland','Magnice (WR area)','onsite','https://www.pracuj.pl/praca/specjalista-ds-personalnych-k-m-magnice-pow-wroclawski,oferta,1005064587','Pracuj.pl','Obsługa personalna w logistyce, Magnice. Opublikowana 8.09.2026.','Lokalny generalist HR blisko WR; mniej international.',3,2,'2026-09-09',true),
('Specjalista ds. Kadr i Onboardingu','ILOGIC','Wrocław, Psie Pole','onsite','https://www.pracuj.pl/praca/specjalista-ds-kadr-i-onboardingu-wroclaw-bierutowska-87,oferta,1005048289','Pracuj.pl','Kadry + onboarding. Opublikowana 9.09.2026.','Onboarding/lifecycle — część core People Ops Marty.',3,2,'2026-09-09',true),
('Polish Payroll Specialist','Fresenius Medical Care EMEA GBS','Wrocław','hybrid','https://www.pracuj.pl/praca/polish-payroll-specialist-wroclaw-plac-nowy-targ-28,oferta,1005074783','Pracuj.pl','Polish payroll w GBS hub WR. Hybrid. Bez DE w tytule.','PL payroll bez DE — lepszy fit niż DE payroll w tym samym hubie.',3,2,'2026-09-09',true),
('HR Specialist with German','Fresenius Medical Care EMEA GBS','Wrocław','hybrid','https://www.pracuj.pl/praca/hr-specialist-with-german-wroclaw-plac-nowy-targ-28,oferta,1005082037','Pracuj.pl','GBS HR specialist DE+EN. Lifecycle/admin. Opublikowana 9.09.2026.','GBS multi-country lifecycle; wymaga DE.',2,3,'2026-09-09',true),
('HR Administration specialist with German','Hewlett Packard Enterprise','Wrocław','hybrid','https://www.pracuj.pl/praca/hr-administration-specialist-with-german-wroclaw,oferta,1005040502','Pracuj.pl','HR admin multi-process delivery, 5.3–10.6k. Hybrid WR. DE required.','HR ops/admin; DE+SSC = niższy fit.',2,3,'2026-09-09',true),
('Payroll Specialist with German','Hewlett Packard Enterprise','Wrocław','hybrid','https://www.pracuj.pl/praca/payroll-specialist-with-german-wroclaw,oferta,1005040529','Pracuj.pl','Payroll DE GBS, 5.8–11.6k. Hybrid WR.','Payroll overlap; DE required.',2,3,'2026-09-09',true),
('Specjalista / Specjalistka ds. kadr i płac','SOLAR FOR YOU','Bielany Wrocławskie','onsite','https://www.pracuj.pl/praca/specjalista-specjalistka-ds-kadr-i-plac-bielany-wroclawskie-pow-wroclawski,oferta,1005049328','Pracuj.pl','Kadrowo-płacowa 6–8k, pracownicy delegowani PL+abroad. Opublikowana 9.09.2026.','Cross-border employment admin — overlap mobility.',3,2,'2026-09-09',true),
('Starszy Specjalista ds. Kadr i Płac','LEONI Kabel Polska','Wierzbice (WR area)','hybrid','https://www.pracuj.pl/praca/starszy-specjalista-starsza-specjalistka-ds-kadr-i-plac-wierzbice-pow-wroclawski-olawska-10,oferta,1005081858','Pracuj.pl','Senior kadry+płace manufacturing, hybrid Wierzbice. Opublikowana 9.09.2026.','Solidne kadry/płace blisko WR; produkcja.',3,2,'2026-09-09',true),
('Specjalista ds. Rekrutacji (K/M/X)','Hasco-Lek / Grupa HASCO','Wrocław','hybrid','https://www.pracuj.pl/praca/specjalista-ds-rekrutacji-k-m-x-wroclaw,oferta,1005061253','Pracuj.pl','Rekrutacja hybrid WR, lokalny pracodawca pharma. Opublikowana 7.09.2026.','Rekrutacja = część scope Marty; Hasco = stabilny lokalny employer.',3,2,'2026-09-09',true),
('Asystent / Asystentka Działu HR','Dallmayr Vending & Office','Wrocław','onsite','https://www.pracuj.pl/praca/asystent-asystentka-dzialu-hr-wroclaw-jana-dlugosza-2,oferta,1005066103','Pracuj.pl','Wsparcie działu HR. Opublikowana 7.09.2026.','Junior HR support — entry, mniejszy match seniority; office-adjacent employer.',2,3,'2026-09-09',true),
('Młodszy specjalista ds. HR','Hilfemed','Wrocław','onsite','https://www.pracuj.pl/praca/mlodszy-specjalista-mlodsza-specjalistka-ds-hr-wroclaw,oferta,1005075784','Pracuj.pl','Junior HR 5.2–5.9k. Opublikowana 7.09.2026.','Za junior względem experience Marty — tylko jeśli otwarci na mid.',2,3,'2026-09-09',true),
('Specjalista / Specjalistka ds. Rekrutacji z j. hiszpańskim','FOLGA','Wrocław','hybrid','https://www.pracuj.pl/praca/specjalista-specjalistka-ds-rekrutacji-z-jezykiem-hiszpanskim-wroclaw,oferta,1005019621','Pracuj.pl','Rekrutacja ES, 5–6.5k. Marta ma ES office exposure.','ES language + rekrutacja — ciekawy overlap z biurem ES, ale czysta rekrutacja.',3,2,'2026-09-09',true);

insert into public.jobs (title, company, location, work_mode, url, source, description, fit_reason, fit_score, priority, verified_at, is_active) values
('Koordynator pracowników z j. hiszpańskim','OPTIVEUM','Wrocław','hybrid','https://www.pracuj.pl/praca/koordynator-koordynatorka-pracownikow-z-j-hiszpanskim-wroclaw,oferta,1005059555','Pracuj.pl','Koordynacja pracowników ES, ~7.5k. Hybrid WR.','ES + people coordination — overlap biur PL+ES Marty.',3,2,'2026-09-09',true),
('Specjalista / Specjalistka ds. Rekrutacji Cudzoziemców','Randstad Polska','Wrocław','hybrid','https://www.pracuj.pl/praca/specjalista-specjalistka-ds-rekrutacji-cudzoziemcow-wroclaw,oferta,1005077273','Pracuj.pl','Rekrutacja cudzoziemców. Hybrid WR. Opublikowana 7.09.2026.','Mobility/foreign employment — blisko Deel multi-country, wąski agency scope.',3,2,'2026-09-09',true),
('HR Advisor with German','Randstad Polska','Wrocław','hybrid','https://www.pracuj.pl/praca/hr-advisor-with-german-wroclaw,oferta,1005055574','Pracuj.pl','HR advisory DE-speaking employees. Hybrid WR.','Advisory/ops; DE required.',2,3,'2026-09-09',true),
('Junior HR Advisor & Payroll with German','Randstad Polska','Wrocław','hybrid','https://www.pracuj.pl/praca/junior-hr-advisor-payroll-with-german-wroclaw,oferta,1005045483','Pracuj.pl','Junior HR+payroll DE. Hybrid WR.','Entry payroll/HR; DE + junior.',2,3,'2026-09-09',true),
('Payroll Project Manager (K/M)','Devire (client)','Remote (HQ WR)','remote','https://www.pracuj.pl/praca/payroll-project-manager-k-m-wroclaw,oferta,1005056179','Pracuj.pl','Payroll PM remote, siedziba WR. Opublikowana 7.09.2026.','Payroll domain + projects; stretch PM, remote z WR.',3,2,'2026-09-09',true),
('People & Culture Specialist','Altavia Kamikaze K2','Łódź (check hybrid/remote)','hybrid','https://rocketjobs.pl/oferta-pracy/altavia-kamikaze-k2-people-culture-specialist-specialistka-lodz-hr-hr','RocketJobs','P&C Specialist title. Łódź — aplikuj tylko jeśli hybrid/relocation OK.','Tytuł P&C idealny; lokalizacja Łódź = warunek geograficzny.',3,2,'2026-09-09',true),
('People & Culture Specialist','Centuria','Poznań','hybrid','https://rocketjobs.pl/oferta-pracy/centuria-people-culture-specialist-poznan-hr-hr','RocketJobs','P&C Specialist Poznań.','Tytuł match; lokalizacja POZ.',3,2,'2026-09-09',true),
('PnC Specialist','Girteka','Poznań','hybrid','https://rocketjobs.pl/oferta-pracy/girteka-pnc-specialist-poznan-hr-hr','RocketJobs','People & Culture Specialist Girteka POZ.','P&C title; international logistics employer.',3,2,'2026-09-09',true),
('People & Culture Partner','LiveKid','Kraków','hybrid','https://rocketjobs.pl/oferta-pracy/livekid-people-culture-partner-krakow-hr-hr','RocketJobs','People & Culture Partner, product/edtech Kraków.','People Partner w produkcie — idealny tytuł; KRK lokalizacja.',4,1,'2026-09-09',true),
('People and Culture Manager','TechTree','Kraków','hybrid','https://rocketjobs.pl/oferta-pracy/techtree-people-and-culture-manager-krakow-hr-hr','RocketJobs','P&C Manager Kraków.','P&C Manager product/tech; stretch seniority + KRK.',3,2,'2026-09-09',true),
('People Partner','SwingDev (a Hippo company)','Warszawa','hybrid','https://rocketjobs.pl/oferta-pracy/swingdev-a-hippo-company-people-partner-warszawa-hr-hr','RocketJobs','People Partner w tech/product WAW.','Dokładny People Partner title w tech — sprawdź remote/hybrid z WR.',4,1,'2026-09-09',true),
('HR Operations Specialist','Aspire Systems Poland','Gdańsk','hybrid','https://rocketjobs.pl/oferta-pracy/aspire-systems-poland-hr-operations-specialist-gdansk-hr-hr','RocketJobs','HR Operations Specialist IT services Gdańsk.','Czysty HR Ops title; lokalizacja GDN.',3,2,'2026-09-09',true);

insert into public.jobs (title, company, location, work_mode, url, source, description, fit_reason, fit_score, priority, verified_at, is_active) values
('Global HR Operations Manager / Interim HR Manager','Optim Human','Warszawa','hybrid','https://rocketjobs.pl/oferta-pracy/optim-human-sp-z-o-o-global-hr-operations-manager-interim-hr-manager-warszawa-hr-hr-e3d995c0','RocketJobs','Global HR Ops Manager / interim. People Operations w opisie.','Global ops title — seniority check; agency interim.',3,2,'2026-09-09',true),
('HR Operations Specialist / HR Admin Specialist','Optim Human','Warszawa','hybrid','https://rocketjobs.pl/oferta-pracy/optim-human-sp-z-o-o-hr-operations-specialist-hr-admin-specialist-warszawa-hr-hr','RocketJobs','HR Ops + admin, Excel/HRIS.','Core People Ops admin title.',3,2,'2026-09-09',true),
('HR Operations and Personnel Administration Manager','State Street','Kraków','hybrid','https://rocketjobs.pl/oferta-pracy/state-street-hr-operations-and-personnel-administration-manager-krakow-hr-hr','RocketJobs','Manager HR ops + personal admin KRK.','Leadership ops/admin — stretch; SSC culture.',2,3,'2026-09-09',true),
('HR Operations & Payroll Projects Specialist','Stock Polska','Warszawa','hybrid','https://rocketjobs.pl/oferta-pracy/stock-polska-hr-operations-payroll-projects-specialist-warszawa-hr-hr','RocketJobs','HR Ops + payroll projects WAW.','Ops+payroll projects — overlap z time-off/payroll Marty.',4,1,'2026-09-09',true),
('HR Generalist Lead (Fixed-term)','Citigroup','Warszawa','hybrid','https://rocketjobs.pl/oferta-pracy/citigroup-hr-generalist-lead---fixed-term-warsaw-hr-hr','RocketJobs','HR Generalist Lead FTC, Citi WAW.','Generalist lead international; FTC + WAW.',3,2,'2026-09-09',true),
('HR Generalist','Lipton Teas and Infusions Poland','Warszawa','hybrid','https://rocketjobs.pl/oferta-pracy/lipton-teas-and-infusions-poland-hr-generalist-warszawa-hr-hr','RocketJobs','HR Generalist WAW.','Classic generalist — dobre jeśli remote/hybrid z WR możliwy.',3,2,'2026-09-09',true),
('Senior HR Generalist','HTH Recruitment (client)','Łódź','hybrid','https://rocketjobs.pl/oferta-pracy/hth-recruitment-senior-hr-generalist-lodz-hr-hr-65fd38f2','RocketJobs','Senior HR Generalist Łódź.','Senior generalist scope match.',3,2,'2026-09-09',true),
('HR Business Partner','Comarch','Kraków','hybrid','https://rocketjobs.pl/oferta-pracy/comarch-s-a-hr-business-partner-krakow-hr-hr-60ed58e1','RocketJobs','HRBP Comarch KRK — duży polski software employer.','HRBP w tech PL; KRK lokalizacja.',3,2,'2026-09-09',true),
('HR Specialist','Comarch','Kraków','hybrid','https://rocketjobs.pl/oferta-pracy/comarch-s-a-hr-specialist-krakow-hr-hr','RocketJobs','HR Specialist Comarch KRK.','HR Specialist tech PL.',3,2,'2026-09-09',true),
('HR Business Partner','dotLinkers','Kraków (+)','hybrid','https://rocketjobs.pl/oferta-pracy/dotlinkers-hr-business-partner-krakow-hr-hr','RocketJobs','HRBP 20–22k, rekrutacja, KP, hybrid KRK+.','Senior HRBP well paid; sprawdź czy WR w lokalizacjach.',3,2,'2026-09-09',true),
('HR Business Partner','DSV GBS','Warszawa','hybrid','https://rocketjobs.pl/oferta-pracy/dsv-gbs-hr-business-partner-warszawa-hr-hr','RocketJobs','HRBP DSV GBS WAW.','HRBP international logistics GBS.',3,2,'2026-09-09',true),
('HR Business Partner','SECO/WARWICK','Świebodzin (+)','hybrid','https://rocketjobs.pl/oferta-pracy/seco-warwick-s-a--hr-business-partner-swiebodzin-hr-hr','RocketJobs','HRBP SECO/WARWICK, reachable z WR (Lubuskie). Performance, talent, engagement.','HRBP blisko regionu Dolny Śląsk/Lubuskie — dojezdne z WR.',4,1,'2026-09-09',true);

insert into public.jobs (title, company, location, work_mode, url, source, description, fit_reason, fit_score, priority, verified_at, is_active) values
('HR Business Partner / Centrum logistyczne 4F','OTCF (4F)','Czeladź','hybrid','https://rocketjobs.pl/oferta-pracy/otcf-s-a--hr-business-partner-centrum-logistyczne-4f-czeladz-hr-hr','RocketJobs','HRBP centrum logistyczne 4F.','HRBP ops/logistics site — hands-on.',3,2,'2026-09-09',true),
('Starszy Specjalista ds. HR – HR Biznes Partner','UNIQA','Warszawa','hybrid','https://rocketjobs.pl/oferta-pracy/uniqa-starszy-a-specjalista-ka-ds-hr---hr-biznes-partner-ka-warszawa-hr-hr','RocketJobs','Senior HR / HRBP UNIQA WAW.','Senior HRBP insurance — corporate mid-size feel.',3,2,'2026-09-09',true),
('Talent Business Partner','HR Hints','Warszawa','hybrid','https://rocketjobs.pl/oferta-pracy/hr-hints-talent-business-partner-warszawa-hr-hr-7fe024ef','RocketJobs','Talent BP WAW.','Partnering + talent; mniej ops.',3,2,'2026-09-09',true),
('Rewards & People Analytics Specialist','Solaris Bus & Coach','Bolechowo','hybrid','https://rocketjobs.pl/oferta-pracy/solaris-bus-coach-sp-z-o-o--rewards-people-analytics-specialist-bolechowo-osiedle-hr-hr','RocketJobs','Rewards + people analytics.','Comp/analytics — partial fit do reporting/insurance work Marty.',3,2,'2026-09-09',true),
('Employee Lifecycle Specialist with German','Mettler Toledo','Warszawa','hybrid','https://rocketjobs.pl/oferta-pracy/mettler-toledo-employee-lifecycle-specialist-with-german-all-genders--warszawa-hr-hr','RocketJobs','Employee Lifecycle Specialist DE, WAW.','Lifecycle title = People Ops core; DE required.',3,2,'2026-09-09',true),
('Specjalista / Specjalistka ds. Kadrowo-Płacowych','ARAW (Agencja Rozwoju Aglomeracji Wrocławskiej)','Wrocław, Plac Solny','onsite','https://www.pracuj.pl/praca/specjalista-specjalistka-ds-kadrowo-placowych-wroclaw-plac-solny-14,oferta,1005023290','Pracuj.pl','Kompleksowa obsługa kadrowo-płacowa, UoP, centrum WR. Min 5 lat doświadczenia.','Lokalny WR employer + twarde kadry/płace; mniej international.',3,2,'2026-09-09',true),
('People Operations Associate','Smith+Nephew','Wrocław','hybrid','https://www.smith-nephew.com/en-us/careers','LinkedIn/aggregator → company careers','People Ops Associate: lifecycle, onboarding, contract changes, payroll support; EN+ES. Hybrid WR hub. Zweryfikuj aktywną requizycję na careers/Workday Smith+Nephew (listing widoczny IX 2026 na agregatorach).','People Ops + EN/ES + international medtech hub WR — bardzo blisko profilu Marty.',5,1,'2026-09-09',true),
('People & HR Operations Specialist','Jabil','Wrocław','hybrid','https://careers.jabil.com/','LinkedIn/aggregator → company careers','People & HR Operations Specialist / HR Administrator hybrid WR. International manufacturing. Sprawdź aktywną ofertę na careers.jabil.com.','People & HR Ops title hybrid WR — mocny match operacyjny.',4,1,'2026-09-09',true);