insert into public.jobs (title, company, location, work_mode, url, source, description, fit_reason, fit_score, priority, verified_at, is_active) values
('Koordynator pracowników z j. hiszpańskim','OPTIVEUM','Wrocław','hybrid','https://www.pracuj.pl/praca/koordynator-koordynatorka-pracownikow-z-j-hiszpanskim-wroclaw,oferta,1005059555','Pracuj.pl','Koordynacja pracowników ES, ~7.5k. Hybrid WR.','ES + people coordination — overlap biur PL+ES Marty.',3,2,'2026-09-09',true),
('Specjalista / Specjalistka ds. Rekrutacji Cudzoziemców','Randstad Polska','Wrocław','hybrid','https://www.pracuj.pl/praca/specjalista-specjalistka-ds-rekrutacji-cudzoziemcow-wroclaw,oferta,1005077273','Pracuj.pl','Rekrutacja cudzoziemców. Hybrid WR. Opublikowana 7.09.2026.','Mobility/foreign employment — blisko Deel multi-country, wąski agency scope.',3,2,'2026-09-09',true),
('HR Advisor with German','Randstad Polska','Wrocław','hybrid','https://www.pracuj.pl/praca/hr-advisor-with-german-wroclaw,oferta,1005055574','Pracuj.pl','HR advisory DE-speaking employees. Hybrid WR.','Advisory/ops; DE required.',2,3,'2026-09-09',true),
('Junior HR Advisor & Payroll with German','Randstad Polska','Wrocław','hybrid','https://www.pracuj.pl/praca/junior-hr-advisor-payroll-with-german-wroclaw,oferta,1005045483','Pracuj.pl','Junior HR+payroll DE. Hybrid WR.','Entry payroll/HR; DE + junior.',2,3,'2026-09-09',true),
('Payroll Project Manager (K/M)','Devire (client)','Remote (HQ WR)','remote','https://www.pracuj.pl/praca/payroll-project-manager-k-m-wroclaw,oferta,1005056179','Pracuj.pl','Payroll PM remote, siedziba WR. Opublikowana 7.09.2026.','Payroll domain + projects; stretch PM, remote z WR.',3,2,'2026-09-09',true),
('People & Culture Specialist','Altavia Kamikaze K2','Łódź (check hybrid/remote)','hybrid','https://rocketjobs.pl/oferta-pracy/altavia-kamikaze-k2-people-culture-specialist-specialistka-lodz-hr-hr','RocketJobs','P&C Specialist title. Łódź — aplikuj tylko jeśli hybrid/relocation OK.','Tytuł P&C idealny; lokalizacja Łódź = warunek geograficzny.',3,2,'2026-09-09',true),
('People & Culture Specialist','Centuria','Poznań','hybrid','https://rocketjobs.pl/oferta-pracy/centuria-people-culture-specialist-poznan-hr-hr','RocketJobs','P&C Specialist Poznań.','Tytuł match; lokalizacja POZ.',3,2,'2026-09-09',true),
('PnC Specialist','Girteka','Poznań','hybrid','https://rocketjobs.pl/oferta-pracy/girteka-pnc-specialist-poznan-hr-hr','RocketJobs','People & Culture Specialist Girteka POZ.','P&C title; international logistics employer.',3,2,'2026-09-09',true),
('People & Culture Partner','LiveKid','Kraków','hybrid','https://rocketjobs.pl/oferta-pracy/livekid-people-culture-partner-krakow-hr-hr','RocketJobs','People & Culture Partner, product/edtech Kraków.','People Partner w produkcie — idealny tytuł; KRK lokalizacja.',4,1,'2026-09-09',true),
('People and Culture Manager','TechTree','Kraków','hybrid','https://rocketjobs.pl/oferta-pracy/techtree-people-and-culture-manager-krakow-hr-hr','RocketJobs','P&C Manager Kraków.','P&C Manager product/tech; stretch seniority + KRK.',3,2,'2026-09-09',true),
('People Partner','SwingDev (a Hippo company)','Warszawa','hybrid','https://rocketjobs.pl/oferta-pracy/swingdev-a-hippo-company-people-partner-warszawa-hr-hr','RocketJobs','People Partner w tech/product WAW.','Dokładny People Partner title w tech — sprawdź remote/hybrid z WR.',4,1,'2026-09-09',true),
('HR Operations Specialist','Aspire Systems Poland','Gdańsk','hybrid','https://rocketjobs.pl/oferta-pracy/aspire-systems-poland-hr-operations-specialist-gdansk-hr-hr','RocketJobs','HR Operations Specialist IT services Gdańsk.','Czysty HR Ops title; lokalizacja GDN.',3,2,'2026-09-09',true);