insert into public.jobs (title, company, location, work_mode, url, source, description, fit_reason, fit_score, priority, verified_at, is_active) values
('HR Business Partner / Partner Biznesowy HR','Aliaxis','Wrocław (IT Hub)','hybrid','https://aliaxis.wd3.myworkdayjobs.com/en-US/Aliaxis/job/PL---Wroclaw/HR-Business-Partner---Partner-Biznesowy-HR_R-57949-1','Workday (Aliaxis careers)','HRBP EEG (PL, RS, LT, HU, CZ, GR) w hubie IT we Wrocławiu. First-line HR dla managerów, onboarding/offboarding, wsparcie rekrutacji, EVP/kultura nowego biura, inicjatywy EMEA HR. PL+EN. PostingAvailable=true (verified 2026-09-09).','Najbliższy fit: multi-country People Ops + HRBP w hubie WR, EN, lifecycle, kultura biura — blisko APMC/Laminar/Deel.',5,1,'2026-09-09',true),
('HR Business Partner','Zrzutka.pl','Wrocław','onsite','https://rocketjobs.pl/oferta-pracy/zrzutka-pl-hr-business-partner-wroclaw-hr-hr','RocketJobs','Senior HRBP soft HR: rozwój, zaangażowanie, rekrutacja, onboarding/EX, compensations, analytics. B2B, stacjonarnie al. Karkonoska 59. Aktywna do ~07.10.2026.','Product company Wrocław + pełny People Partner ownership. Idealny kulturowo (nie GBS).',5,1,'2026-09-09',true),
('HR Specialist','ASTEK Polska','Wrocław','hybrid','https://rocketjobs.pl/oferta-pracy/astek-polska-hr-specialist-wroclaw-hr-hr','RocketJobs','HR operations + administracja kadrowa PL, payroll input, Płatnik/ePUE. Mid, 10–12.5k UoP, hybrid. Oferta aktywna (live).','Twarde People Ops + kadry PL — bezpośrednie przełożenie z payroll/time-off Marty.',4,1,'2026-09-09',true),
('People Operations Coordinator (6–8 Month FTC)','Antal (client)','Wrocław','hybrid','https://rocketjobs.pl/oferta-pracy/antal-sp-z-o-o--people-operations-coordinator-6-8-month-fixed-term-contract--wroclaw-hr-hr','RocketJobs','People Ops Coordinator dla międzynarodowego klienta: HR ops multi-country Europe, Workday, trackery, transformacja procesów. FTC 6–8 mies. Hybrid WR.','Dokładny tytuł People Ops + multi-country + Workday. FTC = bridge, ale scope idealny.',4,1,'2026-09-09',true),
('Regular Payroll Specialist','Spyrosoft','Wrocław','hybrid','https://rocketjobs.pl/oferta-pracy/spyrosoft-regular-payroll-specialist-wroclaw-hr-hr','RocketJobs','Payroll employees+contractors, Enova365, PL labour law, EN B2. 7.2–9.5k. Active ~20 dni.','WR product/IT + contractors/payroll — silny overlap z ARC/Laminar.',4,1,'2026-09-09',true),
('Payroll Specialist (Regular)','Spyrosoft','Wrocław','hybrid','https://rocketjobs.pl/oferta-pracy/spyrosoft-payroll-specialist-regular--wroclaw-hr-hr','RocketJobs','Druga aktywna oferta payroll Spyrosoft WR, hybrid, 7.2–9.5k, Enova365 + EN.','Potwierdzenie otwartego zapotrzebowania payroll/ops w Spyrosoft WR.',4,1,'2026-09-09',true),
('HR Business Partner','EduGO P.S.A.','Remote (PL, listing WR)','remote','https://rocketjobs.pl/oferta-pracy/edugo-p-s-a--hr-business-partner-wroclaw-hr-hr','RocketJobs','HRBP remote, 15–18k UoP, EduTech. Listing dostępny z Wrocławia.','Remote HRBP z PL — da się robić z WR; product/edtech kontekst.',4,1,'2026-09-09',true),
('HR Business Partner Lead / HR Service Delivery Leader','Link Group','Remote (listing WR)','remote','https://rocketjobs.pl/oferta-pracy/link-group-hr-business-partner-lead-hr-service-delivery-leader-wroclaw-hr-hr','RocketJobs','HRBP Lead / Service Delivery, B2B 130–160 PLN/h, remote. Leadership HR service delivery.','Senior People Ops/service delivery remote z WR. Stretch seniority.',3,2,'2026-09-09',true),
('HR Manager','Soliści Adventure Club','Wrocław','onsite','https://rocketjobs.pl/oferta-pracy/solisci-adventure-club-hr-manager-wroclaw-hr-hr','RocketJobs','HR Manager: rekrutacja, budżet, zespół, projekty. UoP/B2B, stacjonarnie WR. Active ~29 dni.','Pełny ownership HR w lokalnej org — generalist; mniejsza skala international.',3,2,'2026-09-09',true),
('Specjalistka / Specjalista ds. płac','VeloBank S.A.','Wrocław','hybrid','https://rocketjobs.pl/oferta-pracy/velobank-s-a--specjalistka-specjalista-ds-plac-wroclaw-hr-hr','RocketJobs','Payroll specialist: prawo pracy, podatki, ZUS. Hybrid WR. Active.','PL payroll overlap; bank = bardziej formalny niż product ops.',3,2,'2026-09-09',true),
('HR Operations Specialist (with German)','Capgemini','Wrocław','hybrid','https://rocketjobs.pl/oferta-pracy/capgemini-hr-operations-specialist-with-german--wroclaw-hr-hr','RocketJobs','HR Ops Specialist, Workday, DE required. Hybrid WR. Wygasa ~3 dni — sprawdź ASAP.','People Ops + Workday, ale DE required + GBS = niższy fit kulturowy.',2,3,'2026-09-09',true);