insert into public.jobs (title, company, location, work_mode, url, source, description, fit_reason, fit_score, priority, verified_at, is_active) values
('Global HR Operations Manager / Interim HR Manager','Optim Human','Warszawa','hybrid','https://rocketjobs.pl/oferta-pracy/optim-human-sp-z-o-o-global-hr-operations-manager-interim-hr-manager-warszawa-hr-hr-e3d995c0','RocketJobs','Global HR Ops Manager / interim. People Operations w opisie.','Global ops title — seniority check; agency interim.',3,2,'2026-09-09',true),
('HR Operations Specialist / HR Admin Specialist','Optim Human','Warszawa','hybrid','https://rocketjobs.pl/oferta-pracy/optim-human-sp-z-o-o-hr-operations-specialist-hr-admin-specialist-warszawa-hr-hr','RocketJobs','HR Ops + admin, Excel/HRIS.','Core People Ops admin title.',3,2,'2026-09-09',true),
('HR Operations and Personnel Administration Manager','State Street','Kraków','hybrid','https://rocketjobs.pl/oferta-pracy/state-street-hr-operations-and-personnel-administration-manager-krakow-hr-hr','RocketJobs','Manager HR ops + personal admin KRK.','Leadership ops/admin — stretch; SSC culture.',2,3,'2026-09-09',true),
('HR Operations & Payroll Projects Specialist','Stock Polska','Warszawa','hybrid','https://rocketjobs.pl/oferta-pracy/stock-polska-hr-operations-payroll-projects-specialist-warszawa-hr-hr','RocketJobs','HR Ops + payroll projects WAW.','Ops+payroll projects — overlap z time-off/payroll Marty.',4,1,'2026-09-09',true),
('HR Generalist Lead (Fixed-term)','Citigroup','Warszawa','hybrid','https://rocketjobs.pl/oferta-pracy/citigroup-hr-generalist-lead---fixed-term-warsaw-hr-hr','RocketJobs','HR Generalist Lead FTC, Citi WAW.','Generalist lead international; FTC + WAW.',3,2,'2026-09-09',true),
('HR Generalist','Lipton Teas and Infusions Poland','Warszawa','hybrid','https://rocketjobs.pl/oferta-pracy/lipton-teas-and-infusions-poland-hr-generalist-warszawa-hr-hr','RocketJobs','HR Generalist WAW.','Classic generalist — dobre jeśli remote/hybrid z WR możliwy.',3,2,'2026-09-09',true),
('Senior HR Generalist','HTH Recruitment (client)','Łódź','hybrid','https://rocketjobs.pl/oferta-pracy/hth-recruitment-senior-hr-generalist-lodz-hr-hr-65fd38f2','RocketJobs','Senior HR Generalist Łódź.','Senior generalist scope match.',3,2,'2026-09-09',true),
('HR Business Partner','Comarch','Kraków','hybrid','https://rocketjobs.pl/oferta-pracy/comarch-s-a-hr-business-partner-krakow-hr-hr-60ed58e1','RocketJobs','HRBP Comarch KRK — duży polski software employer.','HRBP w tech PL; KRK lokalizacja.',3,2,'2026-09-09',true),
('HR Specialist','Comarch','Kraków','hybrid','https://rocketjobs.pl/oferta-pracy/comarch-s-a-hr-specialist-krakow-hr-hr','RocketJobs','HR Specialist Comarch KRK.','HR Specialist tech PL.',3,2,'2026-09-09',true),
('HR Business Partner','dotLinkers','Kraków (+)','hybrid','https://rocketjobs.pl/oferta-pracy/dotlinkers-hr-business-partner-krakow-hr-hr','RocketJobs','HRBP 20–22k, rekrutacja, KP, hybrid KRK+.','Senior HRBP well paid; sprawdź czy WR w lokalizacjach.',3,2,'2026-09-09',true),
('HR Business Partner','DSV GBS','Warszawa','hybrid','https://rocketjobs.pl/oferta-pracy/dsv-gbs-hr-business-partner-warszawa-hr-hr','RocketJobs','HRBP DSV GBS WAW.','HRBP international logistics GBS.',3,2,'2026-09-09',true),
('HR Business Partner','SECO/WARWICK','Świebodzin (+)','hybrid','https://rocketjobs.pl/oferta-pracy/seco-warwick-s-a--hr-business-partner-swiebodzin-hr-hr','RocketJobs','HRBP SECO/WARWICK, reachable z WR (Lubuskie). Performance, talent, engagement.','HRBP blisko regionu Dolny Śląsk/Lubuskie — dojezdne z WR.',4,1,'2026-09-09',true);