insert into public.jobs (title, company, location, work_mode, url, source, description, fit_reason, fit_score, priority, verified_at, is_active) values
('Młodszy Specjalista ds. HR (z j. niemieckim)','Capgemini','Wrocław','hybrid','https://rocketjobs.pl/oferta-pracy/capgemini-mlodszy-a-specjalista-ka-ds-hr-z-j-niemieckim--wroclaw-hr-hr','RocketJobs','Junior HR z DE, Capgemini WR. Active.','WR+HR ops entry; junior+DE = słabszy match seniority/język.',2,3,'2026-09-09',true),
('HR Specialist with German','Pyszne.pl','Wrocław','hybrid','https://rocketjobs.pl/oferta-pracy/pyszne-pl-hr-specialist-with-german-wroclaw-hr-hr','RocketJobs','HR Specialist DE, Just Eat Takeaway brand, hybrid WR.','Product/tech employer WR; DE required obniża fit.',2,3,'2026-09-09',true),
('HR Administrator with German','Pyszne.pl','Wrocław','hybrid','https://rocketjobs.pl/oferta-pracy/pyszne-pl-hr-administrator-with-german-wroclaw-hr-hr','RocketJobs','HR Admin DE, hybrid WR.','Admin/ops overlap; DE required.',2,3,'2026-09-09',true),
('Starszy specjalista ds. Kadr i Płac','WORK 4 US','Oława (WR area)','hybrid','https://rocketjobs.pl/oferta-pracy/work-4-us-spolka-z-ograniczona-odpowiedzialnoscia-starszy-specjalista-ds-kadr-i-plac-olawa-hr-hr','RocketJobs','Senior kadry+płace, delegowanie, A1, Optima, cudzoziemcy. Hybrid Oława.','Cross-border employment admin blisko mobility Marty; lokalizacja Oława.',3,2,'2026-09-09',true),
('HR Business Partner / HR Manager (k/m)','ARCOS FM PL / Saller Polbau','Wrocław, Krzyki','onsite','https://www.pracuj.pl/praca/hr-business-partner-hr-manager-k-m-wroclaw-wyscigowa-56c,oferta,1005047030','Pracuj.pl','Punkt kontaktu HR PL + współpraca z HR DE. Rekrutacja, doradztwo, controlling HR. Opublikowana 8.09.2026.','Generalist HRBP + ops + rekrutacja. Cross-border DE (atut, nie hard gate w tytule).',4,1,'2026-09-09',true),
('HR Business Partner (HRBP) (K/M)','Atlas Ward Polska','Wrocław, Krzyki','hybrid','https://www.pracuj.pl/praca/hr-business-partner-hrbp-k-m-wroclaw-zwycieska-41,oferta,1005044437','Pracuj.pl','HRBP hybrid WR. Partner biznesowy dla managerów. Opublikowana 5.09.2026.','Klasyczny HRBP hybrid we Wrocławiu — dobry fit partnerski.',4,1,'2026-09-09',true),
('HR Business Partner','LHH (klient produkcyjny)','Wrocław','onsite','https://www.pracuj.pl/praca/hr-business-partner-wroclaw,oferta,1005018441','Pracuj.pl','HRBP dla klienta produkcyjnego: lifecycle, onboarding, rozwój, KPIs, EN. 11–15k. Uwaga: wygasa ~09.09 — sprawdź status przed aplikacją.','HRBP generalist + data/KPI; produkcja ≠ tech, ale solidny scope.',3,2,'2026-09-09',true),
('HR Manager / HR Builder','Human Group','Wrocław','hybrid','https://www.pracuj.pl/praca/hr-manager-hr-builder-wroclaw,oferta,1005031044','Pracuj.pl','Hands-on HR builder: procesy, rekrutacja, dane, AI/automatyzacja. Hybrid. Ważna do ~16.09.2026.','Szeroki ownership People/HR (nie wąski SSC). Uwaga: agencja, nie product.',4,1,'2026-09-09',true),
('HR Business Partner Grupy (k/m)','Human Group','Wrocław','hybrid','https://www.pracuj.pl/praca/hr-business-partner-grupy-k-m-wroclaw,oferta,1005013549','Pracuj.pl','Partnerstwo z zarządem, onboarding/offboarding, rekrutacja wewnętrzna, polityki HR. 13–18k. Hybrid.','Builder/HRBP ownership — sprawczość jak w mid-size ops.',4,1,'2026-09-09',true),
('HR Operations & Process Specialist','DEKRA (international client)','Wrocław','onsite','https://www.pracuj.pl/praca/hr-operations-process-specialist-wroclaw,oferta,1005049577','Pracuj.pl','Analyze/document HR ops across multiple countries; standardize processes; local compliance. Opublikowana 8.09.2026.','Multi-country HR process ownership — bardzo blisko global people ops Marty.',5,1,'2026-09-09',true),
('HR & Executive Support Specialist','Erste Operations GmbH','Wrocław','hybrid','https://www.pracuj.pl/praca/hr-executive-support-specialist-wroclaw-strzegomska-8-10,oferta,1005039762','Pracuj.pl','Employee lifecycle (recruitment, onboarding, offboarding), dokumentacja, wsparcie local management. 7.5–9.5k. Hybrid/onsite.','Lifecycle + office/exec support — overlap z People & Ops / office coordination.',4,1,'2026-09-09',true),
('Specjalistka / Specjalista ds. Wsparcia Aplikacji HR','Credit Agricole Bank Polska','Wrocław','hybrid','https://www.pracuj.pl/praca/specjalistka-specjalista-ds-wsparcia-aplikacji-hr-wroclaw-legnicka-48,oferta,1005069654','Pracuj.pl','Wsparcie systemów HR, platformy benefitowe, monitoring aplikacji, współpraca z dostawcami. HQ WR.','HRIS/ops systems — Marta zna Deel/HR records; fit techniczno-operacyjny.',3,2,'2026-09-09',true);