insert into public.jobs (title, company, location, work_mode, url, source, description, fit_reason, fit_score, priority, verified_at, is_active) values
('Specjalista ds. Personalnych (K/M)','CEVA Logistics Poland','Magnice (WR area)','onsite','https://www.pracuj.pl/praca/specjalista-ds-personalnych-k-m-magnice-pow-wroclawski,oferta,1005064587','Pracuj.pl','Obsługa personalna w logistyce, Magnice. Opublikowana 8.09.2026.','Lokalny generalist HR blisko WR; mniej international.',3,2,'2026-09-09',true),
('Specjalista ds. Kadr i Onboardingu','ILOGIC','Wrocław, Psie Pole','onsite','https://www.pracuj.pl/praca/specjalista-ds-kadr-i-onboardingu-wroclaw-bierutowska-87,oferta,1005048289','Pracuj.pl','Kadry + onboarding. Opublikowana 9.09.2026.','Onboarding/lifecycle — część core People Ops Marty.',3,2,'2026-09-09',true),
('Polish Payroll Specialist','Fresenius Medical Care EMEA GBS','Wrocław','hybrid','https://www.pracuj.pl/praca/polish-payroll-specialist-wroclaw-plac-nowy-targ-28,oferta,1005074783','Pracuj.pl','Polish payroll w GBS hub WR. Hybrid. Bez DE w tytule.','PL payroll bez DE — lepszy fit niż DE payroll w tym samym hubie.',3,2,'2026-09-09',true),
('HR Specialist with German','Fresenius Medical Care EMEA GBS','Wrocław','hybrid','https://www.pracuj.pl/praca/hr-specialist-with-german-wroclaw-plac-nowy-targ-28,oferta,1005082037','Pracuj.pl','GBS HR specialist DE+EN. Lifecycle/admin. Opublikowana 9.09.2026.','GBS multi-country lifecycle; wymaga DE.',2,3,'2026-09-09',true),
('HR Administration specialist with German','Hewlett Packard Enterprise','Wrocław','hybrid','https://www.pracuj.pl/praca/hr-administration-specialist-with-german-wroclaw,oferta,1005040502','Pracuj.pl','HR admin multi-process delivery, 5.3–10.6k. Hybrid WR. DE required.','HR ops/admin; DE+SSC = niższy fit.',2,3,'2026-09-09',true),
('Payroll Specialist with German','Hewlett Packard Enterprise','Wrocław','hybrid','https://www.pracuj.pl/praca/payroll-specialist-with-german-wroclaw,oferta,1005040529','Pracuj.pl','Payroll DE GBS, 5.8–11.6k. Hybrid WR.','Payroll overlap; DE required.',2,3,'2026-09-09',true),
('Specjalista / Specjalistka ds. kadr i płac','SOLAR FOR YOU','Bielany Wrocławskie','onsite','https://www.pracuj.pl/praca/specjalista-specjalistka-ds-kadr-i-plac-bielany-wroclawskie-pow-wroclawski,oferta,1005049328','Pracuj.pl','Kadrowo-płacowa 6–8k, pracownicy delegowani PL+abroad. Opublikowana 9.09.2026.','Cross-border employment admin — overlap mobility.',3,2,'2026-09-09',true),
('Starszy Specjalista ds. Kadr i Płac','LEONI Kabel Polska','Wierzbice (WR area)','hybrid','https://www.pracuj.pl/praca/starszy-specjalista-starsza-specjalistka-ds-kadr-i-plac-wierzbice-pow-wroclawski-olawska-10,oferta,1005081858','Pracuj.pl','Senior kadry+płace manufacturing, hybrid Wierzbice. Opublikowana 9.09.2026.','Solidne kadry/płace blisko WR; produkcja.',3,2,'2026-09-09',true),
('Specjalista ds. Rekrutacji (K/M/X)','Hasco-Lek / Grupa HASCO','Wrocław','hybrid','https://www.pracuj.pl/praca/specjalista-ds-rekrutacji-k-m-x-wroclaw,oferta,1005061253','Pracuj.pl','Rekrutacja hybrid WR, lokalny pracodawca pharma. Opublikowana 7.09.2026.','Rekrutacja = część scope Marty; Hasco = stabilny lokalny employer.',3,2,'2026-09-09',true),
('Asystent / Asystentka Działu HR','Dallmayr Vending & Office','Wrocław','onsite','https://www.pracuj.pl/praca/asystent-asystentka-dzialu-hr-wroclaw-jana-dlugosza-2,oferta,1005066103','Pracuj.pl','Wsparcie działu HR. Opublikowana 7.09.2026.','Junior HR support — entry, mniejszy match seniority; office-adjacent employer.',2,3,'2026-09-09',true),
('Młodszy specjalista ds. HR','Hilfemed','Wrocław','onsite','https://www.pracuj.pl/praca/mlodszy-specjalista-mlodsza-specjalistka-ds-hr-wroclaw,oferta,1005075784','Pracuj.pl','Junior HR 5.2–5.9k. Opublikowana 7.09.2026.','Za junior względem experience Marty — tylko jeśli otwarci na mid.',2,3,'2026-09-09',true),
('Specjalista / Specjalistka ds. Rekrutacji z j. hiszpańskim','FOLGA','Wrocław','hybrid','https://www.pracuj.pl/praca/specjalista-specjalistka-ds-rekrutacji-z-jezykiem-hiszpanskim-wroclaw,oferta,1005019621','Pracuj.pl','Rekrutacja ES, 5–6.5k. Marta ma ES office exposure.','ES language + rekrutacja — ciekawy overlap z biurem ES, ale czysta rekrutacja.',3,2,'2026-09-09',true);